import Head from "next/head";
import Navbar from "../components/Navbar";
import { Box, Container, Text, Button } from "@chakra-ui/react";
import PrimaryButton from "../utils/PrimaryButton";
import Lottie from "react-lottie-player";
import { BsGithub } from "react-icons/bs";
import lottieAnimation from "../utils/lottie-animation.json";
import twitterLogo from "../assets/icons/twitter-logo.png";
import Image from "next/image";

type StaticImageData = {
  src: string;
  height: number;
  width: number;
  blurDataURL?: string;
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          Sorta Server | The No.1 Application for sorting twitter bookmarks
        </title>
        <meta name="description" content="Generated by create next app" />

        <link
          rel="shortcut icon"
          href="https://res.cloudinary.com/dz37h4oq1/image/upload/v1665962584/all/sorta-logo_oe303b.png"
        />
      </Head>
      <Navbar />
      <Container
        display="flex"
        flexDirection="column"
        justifyContent="center"
        alignItems="center"
      >
        <Box
          mt="150px"
          display="flex"
          justifyContent="center"
          alignItems={"center"}
          flexDirection="column"
        >
          <Text
            textAlign="center"
            fontSize="4xl"
            fontWeight="800"
            textTransform="capitalize"
            fontFamily="Avenir Black"
            py="5"
          >
            The No. 1 application for sorting your twitter bookmarks
          </Text>
          {/* <Box width={50} height={50} position="relative">
            <img
              src="https://res.cloudinary.com/dz37h4oq1/image/upload/v1665964275/all/twitter-lofo_ldpuqu.png"
              alt=""
            />
          </Box> */}
          <Box
            border="1px"
            borderRadius="10"
            width={{ base: "400px", md: "400px" }}
            height="400px"
            display="flex"
            mb="10"
            justifyContent="center"
          >
            <Lottie
              loop
              animationData={lottieAnimation}
              play
              style={{ width: "100%", height: "100%" }}
            />
          </Box>
        </Box>
        <Box display="flex" gap="5">
          <PrimaryButton />
          <Button colorScheme="blue" variant="solid" display="flex" gap="2">
            Contribute <BsGithub />
          </Button>
        </Box>
      </Container>
    </div>
  );
}
